[profile.default]
src = 'contracts'
out = 'out'
test = 'tests'
# Include test contracts for ABI generation
extra_output_files = ["abi"]
libs = ['../../lib', '../../lib/openzeppelin-contracts/lib', "../utils"]
remappings = [
    '@0x/contracts-utils/=../utils/',
]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 1000000
evm_version = "shanghai"
ignored_error_codes = [5856]
fs_permissions = [
    { access = "read", path = "./" },
    { access = "read", path = "../" }
] 