[profile.default]
src = 'contracts/src'
out = 'out'
test = 'tests'
libs = ['lib', '../utils', '../erc20', '../assert-proxy', '../exchange-libs']
remappings = [
    '@0x/contracts-utils/=../utils/',
    '@0x/contracts-erc20/=../erc20/',
    '@0x/contracts-asset-proxy/=../asset-proxy/',
    '@0x/contracts-exchange-libs/=../exchange-libs/',
]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 1000000
evm_version = "shanghai"
fs_permissions = [
    { access = "read", path = "./" },
    { access = "read", path = "../" }
]