[profile.default]
src = 'contracts/src'
out = 'out'
test = 'tests'
# 排除 Hardhat 测试辅助合约，避免被 Foundry 识别为测试
no_match_path = "contracts/test/*"
extra_output_files = ["abi"]
libs = ['lib', '../utils/contracts/src/']
remappings = [
    '@0x/contracts-utils/=../utils/',
]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 1000000
evm_version = "shanghai"
fs_permissions = [
    { access = "read", path = "./" },
    { access = "read", path = "../" }
]