[profile.default]
src = 'contracts/src'
out = 'out'
test = 'tests'
# Include test contracts for ABI generation
extra_output_files = ["abi"]
libs = ['../../lib', "../erc20/contracts/", "../governance/contracts/"]
remappings = [
    '@0x/contracts-erc20/=../erc20/',
    '@0x/contracts-governance/=../governance/',
]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
fs_permissions = [
    { access = "read", path = "./" },
    { access = "read", path = "../" }
] 