[profile.default]
src = 'contracts/src'
out = 'out'
test = 'tests'
libs = ['lib']
remappings = [
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@0x/contracts-utils/=../utils/',
]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 1000000
evm_version = "cancun"
fs_permissions = [
    { access = "read", path = "./" },
    { access = "read", path = "../" }
]

via_ir = true

[profile.integration]
match_path = "tests/integration/*.sol"
gas_price = 31_000_000_000

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

[profile.smt.model_checker]
engine = 'chc'
timeout = 10_000
targets = [
    'assert',
    'constantCondition',
    'divByZero',
    'outOfBounds',
    'underflow'
]
contracts = { 'contracts/ZeroExProtocolGovernor.sol' = [ 'ZeroExProtocolGovernor' ] }
