[profile.default]
src = 'contracts/src'
out = 'foundry-artifacts'
test = 'test'
libs = ["lib/", "../utils/", "../erc20/", "../zero-ex/"]
remappings = [
    '@0x/contracts-utils/=../utils/',
    '@0x/contracts-erc20/=../erc20/',
    '@0x/contracts-zero-ex/=../zero-ex/',
]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 1000000
fs_permissions = [
    { access = "read", path = "./" },
    { access = "read", path = "../" },
    { access = "read", path = "../../" }
]

# 兼容性设置
evm_version = "cancun"
via_ir = false

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/6770454bc6ea42c58aac12978531b93f" 